spring:
  datasource:
    url: jdbc:h2:mem:mybrickdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

springdoc:
  packagesToScan: com.sullivan.ricksbricks.controllers
  api-docs:
    path: /api-docs